main: io.github.lasercar.spectatetp.SpectateTP
author: Lasercar7
website: https://github.com/lasercar/SpectateTP
name: SpectateTP
version: 1.2.0
description: Requires permission to teleport using spectator mode.
permissions:
  spectate.tp:
    description: Allows player to teleport using spectator mode.
